### ISSUE TITLE
All filex history seems to have been lost in the transition to the new repo under eclipse-threadx 

### ISSUE THREAD

**Issue by nettercm** [eclipse-threadx/filex#44]
For all the other repos, i.e. threadx, netxduo, etc.,  all the file history from the original azure-rtos repos is still available.  Not so with filex.   Can this be resolved?

**Comment by wickste** [comment]
@nettercm yes, this was an intentional decision driven by the business. This cannot be resolved. If there is a specific ask or need for anything from the history, please file an issue with additional detail that we can follow up on.
