### ISSUE TITLE
How to partition and format an SD card using filex functions?

### ISSUE THREAD

**Issue by XingYeKM** [eclipse-threadx/filex#58]
The function fx_media_format appears to format the SD card only as a whole partition？

**Comment by nflandin** [comment]
I am not a contributor to this project, but will offer my best understanding (as nobody else appears to be available.

Within FileX, "media" seems to refer to one specific partition on one specific device. Most of the example drivers that I've seen are written with the intent of creating (only) one partition, which begins at the base address of the memory area. This is not necessary, and you can definitely implement multiple partitions within a device You can do this by writing (or customizing) the fx_media_driver, and it can be made quite simple if you pass in some info about the size and location of the desired partition via driver_info_ptr.
