### ISSUE TITLE
If I port Filex to another RTOS without TheadX, do I need to maintain read/write protection in multithreading?

### ISSUE THREAD

**Issue by XingYeKM** [eclipse-threadx/filex#60]
I noticed that read and write protection in Filex is done with the macro definition FX_PROTECT, which uses ThreadX.
![123](https://github.com/user-attachments/assets/58707953-e9b0-41db-af3b-d311d098e85b)

**Comment by nflandin** [comment]
In short, yes.

Attempting to access a filesystem from one thread while another thread is modifying it can lead to many problems. If you have more than one thread modifying and/or accessing any filesystem, you need to have some way of protecting against potential problems. This can take the form of the FX_PROTECT/FX_UNPROTECT mutex macros, or an infinite number of other possibilities.

**Comment by XingYeKM** [comment]
Thanks @nflandin 
I know what to do, okay
