### ISSUE TITLE
exFAT support

### ISSUE THREAD

**Issue by vlang-intona** [eclipse-threadx/filex#65]
Would be cool. exFAT is patented, but it's not a copyright issue - anyone can implement exFAT and publish such an implementation.

**Comment by fdesbiens** [comment]
Thank you for this request, @vlang-intona.

You are correct to state this is not a copyright issue. But patents are serious issues too.

The Eclipse Foundation will not accept contributions that willfully infringe on a patent. This would create significant legal liability for us.  

Anyone with a proper license to the relevant patent(s) can implement exFAT. However, getting such a license to cover FileX would be expensive, and we lack financial resources.

Naturally, we can explore licensing the relevant patents if enough ThreadX and FileX users are willing to fund the initiative.

**Comment by vlang-intona** [comment]
That's interesting. I didn't know all the FAT patents (except exFAT) have run out, which is implied by your statement.

Note that under azure-rtos, Microsoft did offer a free exFAT license on certain platforms: https://github.com/azure-rtos/filex/?tab=readme-ov-file#exfat-licensing

This seems unavailable now with the move to Eclipse, all while azure-rtos/filex was set to read-only.

**Comment by fdesbiens** [comment]
@vlang-intona Yes, older versions of FAT are patent-free. They can be freely implemented.

Whatever license Microsoft offered for Azure RTOS does not apply to Eclipse ThreadX. Do not forget Azure RTOS involved a commercial license unless you were using hardware from Microsoft's major silicon partners, which came bundled with such license.

So, unless you have a valid Azure RTOS license, you cannot use exFAT. Microsoft discontinued the sales of such licenses.

**Comment by vlang-intona** [comment]
@fdesbiens We are covered by such a hardware license (the chip is listed in the previous FileX license). Looks like we have to stay with the old azure-rtos snapshot for now. Thank you for the clarifications.

**Comment by fdesbiens** [comment]
I am closing this issue since the exchange has concluded.
